### ISSUE TITLE
Mysql "Deadlock" error caurse by .add(new_tag_name) function

### ISSUE THREAD

**Issue by yeruizhi** [jazzband/django-taggit#234]
My django model Student has tag fields.

When calling `student.tags.add(tag_str)` ,  if tag_str is one tag name that already exists, this call will success, but if this tag_str in one new tag name that never been used in my system before, this call will cause an 'Deadlock' error.

```
ERROR 14-05-01 08:25:09      ajax : save_student_tags
Traceback (most recent call last):
  File "/home/jifenzhong/project/dayi.im/dayi/note/ajax.py", line 32, in save_student_tags
    student.tags.add(tag_str)
  File "/usr/local/lib/python2.7/dist-packages/taggit/utils.py", line 128, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/taggit/managers.py", line 389, in add
    tag_objs.add(self.through.tag_model().objects.create(name=new_tag))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 149, in create
    return self.get_query_set().create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 416, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/taggit/models.py", line 40, in save
    res = super(TagBase, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 128, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

```

**What should I do to avoid this and make adding new tag function successfully? Thanks**

**Comment by rtpg** [comment]
I'm going to have to agree that this feels like something else going on here. Closing this one for now
