### ISSUE TITLE
get related model recursive error

### ISSUE THREAD

**Issue by bemall** [jazzband/django-taggit#331]
For this error, I am able to install django-taggit==0.16.2 just fine. But when I attempt a migrate to a new database I get this error.

django-taggit==0.16.2
django-taggit-templatetags2==1.4.0
django-1.8.3

Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "//lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(_args, *_options)
  File  /lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/lib/python2.7/site-packages/django/db/migrations/executor.py", line 104, in migrate
    state = migration.mutate_state(state, preserve=do_run)
  File "/lib/python2.7/site-packages/django/db/migrations/migration.py", line 83, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 51, in state_forwards
    state.reload_model(app_label, self.model_name_lower)
  File "//lib/python2.7/site-packages/django/db/migrations/state.py", line 122, in reload_model
    related_models.update(get_related_models_recursive(rel_model))
  File "//lib/python2.7/site-packages/django/db/migrations/state.py", line 57, in get_related_models_recursive
    rel_app_label, rel_model_name = rel_mod._meta.app_label, rel_mod._meta.model_name
AttributeError: 'NoneType' object has no attribute '_meta'
(oneeight_v)

**Comment by ricardoanjinho** [comment]
Exact same symptom, any hint on this subject would be greatly appreciated. No clues on the reason behind, for the time being.

Thanks in advance

**Comment by sonnguyenthai** [comment]
Using a "through model" will resolve this error: https://django-taggit.readthedocs.org/en/latest/custom_tagging.html

**Comment by rtpg** [comment]
Going to close this one, I think that this might have been related to `related_name` stuff from before but this is a hard issue to debug without more information (like the migrations itself). Please re-open if still valid (with some more info)
