### ISSUE TITLE
Using taggit together with simple history makes migrations non-portable

### ISSUE THREAD

**Issue by amcpherson** [jazzband/django-taggit#501]
When I use the following to track history of tags:

```
import taggit.models
import simple_history
simple_history.register(taggit.models.Tag)
```

makemigrations creates migrations in the taggit migrations directory under site packages.  If i then try to bring up the database on another server, those migrations are not found:

```
Traceback (most recent call last):
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/amcphers/Anaconda/envs/tantalus/lib/python2.7/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration tantalus.0001_initial dependencies reference nonexistent parent node (u'taggit', u'0004_historicaltag_history_change_reason')
```

**Comment by rtpg** [comment]
if you want to modify the base `taggit` `Tag` model, you should re-declare it in your source tree (what's happening for you is that the migration is being created in your libs instead of your source code). We can't really do much about this problem, it's kind of fundamental to how django migrations work.

Would be worth an FAQ entry tho
