### ISSUE TITLE
no such table: django_content_type when starting new project in tags.most_common()

### ISSUE THREAD

**Issue by AllanNozomu** [jazzband/django-taggit#532]
I was working in a project using django_rest_framework and taggit. But I switched computers and I needed to reinstall the database. But, when I tried to run `./manage.py migrate` to install the migrations, this error appeared: The project that I used to simulate this error is this [test project](https://github.com/AllanNozomu/taggit-test).

I am using python 3

```
Traceback (most recent call last):
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/taggit/managers.py", line 94, in get_queryset
    return self.instance._prefetched_objects_cache[self.prefetch_cache_name]
AttributeError: 'NoneType' object has no attribute '_prefetched_objects_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_content_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/allan/Documents/taggit-test/taggit_test/taggit_test/urls.py", line 19, in <module>
    from products import views
  File "/home/allan/Documents/taggit-test/taggit_test/products/views.py", line 6, in <module>
    class TagViewSet(viewsets.ModelViewSet):
  File "/home/allan/Documents/taggit-test/taggit_test/products/views.py", line 7, in TagViewSet
    queryset = Product.tags.most_common()
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/taggit/managers.py", line 317, in most_common
    queryset = self.get_queryset(extra_filters).annotate(
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/taggit/managers.py", line 97, in get_queryset
    return self.through.tags_for(self.model, self.instance, **kwargs)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/taggit/models.py", line 177, in tags_for
    ct = ContentType.objects.get_for_model(model)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 51, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/allan/Documents/taggit-test/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_content_type
```

What I noticed: `Product.tags.most_common()` is causing this problem somehow. I can't even run `./manage.py showmigrations`. 

**WORKAROUND**: If I just change this command by `Products.objects.all()` (just to not use this most_common function), the error disappears and it is now possible to migrate. Then, just change back to most_common function.

 Thanks for considering my request.

**Comment by MSBPeace** [comment]
I am having a similar issue when deploying to AWS Beanstalk environments only, running locally seems to be fine. The suggested workaround does not seem to work for me. Ideas are welcome.
