### ISSUE TITLE
`get_extra_restriction()` missing required positional argument related_alias

### ISSUE THREAD

**Issue by bsiebens** [jazzband/django-taggit#776]
Using Django-Taggit on Django 4.0rc1 (running on Python 3.9). I have a model called TransactionJournal that contains following line:

`tags = TaggableManager(blank=True)`

Querying the model with the following statement results in the below error:

`TransactionJournal.objects.filter(tags__name__in=["t1", "t2"])`

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/query.py", line 256, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1189, in execute_sql
    sql, params = self.as_sql()
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 545, in as_sql
    from_, f_params = self.get_from_clause()
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 833, in get_from_clause
    clause_sql, clause_params = self.compile(from_clause)
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 463, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/sql/datastructures.py", line 81, in as_sql
    extra_cond = self.join_field.get_extra_restriction(self.table_alias, self.parent_alias)
  File "/Users/XXX/.local/share/virtualenvs/YYY-rEzd9bfd/lib/python3.9/site-packages/django/db/models/fields/reverse_related.py", line 168, in get_extra_restriction
    return self.field.get_extra_restriction(related_alias, alias)
TypeError: get_extra_restriction() missing 1 required positional argument: 'related_alias'`

Any thoughts on what might be causing this?

**Comment by rtpg** [comment]
We don't have support for Django 4.0 just yet (it's not even being tested in CI), but according to [the release notes of Django 4.0](https://docs.djangoproject.com/en/dev/releases/4.0/#miscellaneous) the signature for `get_extra_restriction` changed (the `where_class` parameter is no longer used).

So yeah, this is something that will likely get fixed with Django 4.0 support

**Comment by Hakonta** [comment]
I'm experiencing the same issue. 

Please let us know if anyone finds any workarounds for this issue in the meantime.
