### ISSUE TITLE
Related Field got invalid lookup: name

### ISSUE THREAD

**Issue by pljspahn** [jazzband/django-taggit#825]
I have a ListView that displays a filtered set of my model instances based on the tag.
```

class TagListView(ListView):
    model = Mymodel
    paginate_by = 20
    allow_empty = False

    def get_queryset(self):
        #Error is referencing this line - it can't find "name" as a related field
        queryset = Mymodel.objects.filter(tags__name__in=[self.kwargs['slug']])
        
        return queryset

    def get_context_data(self, **kwargs):
        featured_items = self.get_queryset().filter(tags__name='featured')[:6]

        context = super().get_context_data(**kwargs)
        context['page'] = {
            'title': deslugify(self.kwargs['slug']),
        }
        context['featured_items'] = featured_items
        return context
```

This has been working fine. I updated to Django to 4.1.2 and Wagtail to 4.0.4 yesterday, which seems to have broken this view, which now presents the Related Field lookup error.

It was the end of the day when I did the upgrades, and I think I messed up and forgot to refreeze my requirements.txt file, so some dependency versions got mixed up. I fixed a few of them manually, but this error tells me I think I may have missed something.

I've looked through various migration files and don't see any changes to the Tag model (as if "name" was changed to something else). 

**What is the source of this error, did I miss something in some release notes somewhere?**

**Comment by pljspahn** [comment]
Just wanted to add that there was a seemingly related error I also have on the admin list view for `Mymodel` using tags field.

When I include tags in `list_filter`:

    class MymodelAdmin(admin.ModelAdmin):
        ...
        list_filter = ('tags',)
        ...


the admin list view throws error:

    NotRelationField at /django-admin/mymodels/mymodel
    No exception message supplied

**Comment by robdoesstuff** [comment]
Are you running 3.0.0? I had this problem under 2.1.0 but not under latest.

**Comment by rtpg** [comment]
@pljspahn could you confirm if you are on 3.0.0? Also, please post a stack trace

**Comment by auslaner** [comment]
I also had this in 2.1.0 but it is resolved under 3.0.0. This was my traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/views.py", line 28, in serve
    return page.serve(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/routable_page/models.py", line 171, in serve
    return view(request, *args, **kwargs)
  File "/code/blog/models.py", line 119, in post_by_tag
    self.posts = self.get_posts().filter(tags__name=tag)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1292, in build_lookup
    raise FieldError(
django.core.exceptions.FieldError: Related Field got invalid lookup: name
```

**Comment by rcwestlake** [comment]
I also had this issue on an older version but it resolved on the latest.

**Comment by rtpg** [comment]
Alright, thank you for the comments both of you. I'm going to consider this a resolved issue. Anyone else hitting this, please make sure to be at least on `3.0.0`. If you are and are hitting this issue, please comment/reopen
