### ISSUE TITLE
get() returned more than one Tag -- it returned 2!

### ISSUE THREAD

**Issue by naskio** [jazzband/django-taggit#826]
Hello
Sometimes when adding tags to an existing object, I am getting the following error.
```
get() returned more than one Tag -- it returned 2!
```
Here is the code I am using
```python3
...
publication.tags.set(all_tags, clear=True)
publication.save()
# I also tried
publication.tags.set(all_tags)
publication.save()
# and
publication.tags.add(*all_tags)
publication.save()
# but still getting the same issue
...
```
**Notes**:
- I am not using any get function
- Django version 4.1

**Comment by rtpg** [comment]
@naskio do you have a longer stack trace? please post more details.

**Comment by naskio** [comment]
```
2022-11-16 01:06:22.022 | ERROR    | apps.data_collection.management.commands.tagging:handle:69 - get() returned more than one Tag -- it returned 2!
Traceback (most recent call last):

> File "/app/apps/data_collection/management/commands/tagging.py", line 63, in handle
    publication.tags.set(all_tags, clear=True)
    │           │        └ ['libération', 'Direction', 'Algérie Presse Service', 'guerre de libération', 'EN', 'Communauté nationale', 'Vidéo', 'Abdelma...
    │           └ <taggit.managers.TaggableManager: tags>
    └ <Publication: La communauté algérienne en Libye commémore le 68e anniversaire du déclenchement de la Glorieuse guerre de libé...

  File "/usr/local/lib/python3.9/site-packages/taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
           │    │      │       └ {'clear': True}
           │    │      └ (['libération', 'Direction', 'Algérie Presse Service', 'guerre de libération', 'EN', 'Communauté nationale', 'Vidéo', 'Abdelm...
           │    └ <taggit.managers._TaggableManager object at 0x7ff903015be0>
           └ <function _TaggableManager.set at 0x7ff90e52dee0>
  File "/usr/local/lib/python3.9/site-packages/taggit/managers.py", line 273, in set
    self.add(*tags, **kwargs)
    │    │    │       └ {}
    │    │    └ ['libération', 'Direction', 'Algérie Presse Service', 'guerre de libération', 'EN', 'Communauté nationale', 'Vidéo', 'Abdelma...
    │    └ <function _TaggableManager.add at 0x7ff90e52db80>
    └ <taggit.managers._TaggableManager object at 0x7ff903015be0>
  File "/usr/local/lib/python3.9/site-packages/taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
           │    │      │       └ {}
           │    │      └ ('libération', 'Direction', 'Algérie Presse Service', 'guerre de libération', 'EN', 'Communauté nationale', 'Vidéo', 'Abdelma...
           │    └ <taggit.managers._TaggableManager object at 0x7ff903015be0>
           └ <function _TaggableManager.add at 0x7ff90e52daf0>
  File "/usr/local/lib/python3.9/site-packages/taggit/managers.py", line 152, in add
    tag_objs = self._to_tag_model_instances(tags, tag_kwargs)
               │    │                       │     └ {}
               │    │                       └ ('libération', 'Direction', 'Algérie Presse Service', 'guerre de libération', 'EN', 'Communauté nationale', 'Vidéo', 'Abdelma...
               │    └ <function _TaggableManager._to_tag_model_instances at 0x7ff90e52dc10>
               └ <taggit.managers._TaggableManager object at 0x7ff903015be0>
  File "/usr/local/lib/python3.9/site-packages/taggit/managers.py", line 223, in _to_tag_model_instances
    tag = manager.get(name__iexact=name)
          │       │                └ 'UN'
          │       └ <function QuerySet.get at 0x7ff910d86f70>
          └ <QuerySet [<Tag: South Korea>, <Tag: India>, <Tag: Canadian>, <Tag: Australia>, <Tag: Barça>, <Tag: Xavi>, <Tag: Ukraine>, <T...
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 499, in get
    raise self.model.MultipleObjectsReturned(
          │    │     └ <class 'taggit.models.Tag.MultipleObjectsReturned'>
          │    └ <class 'taggit.models.Tag'>
          └ <QuerySet [<Tag: South Korea>, <Tag: India>, <Tag: Canadian>, <Tag: Australia>, <Tag: Barça>, <Tag: Xavi>, <Tag: Ukraine>, <T...

taggit.models.Tag.MultipleObjectsReturned: get() returned more than one Tag -- it returned 2!
```

**NOTE**:
At the begging I inserted many tags without having `TAGGIT_CASE_INSENSITIVE = True` but I added it later.
so I guess that I may have inserted some tags (for example `UKRAINE` and `Ukraine`) which were not the same but became equal after enabling case insensitivity (having duplicates in the DB).

**Comment by rtpg** [comment]
@naskio thank you very much for that detail! It sounds very important.

If in your system you have that problem, the easiest thing to do would be to normalize manually in a database migration. So for example you find all of the `TaggedItem`s that are pointing to `UKRAINE` and then point them to `Ukraine`. From there, you should be able to delete `UKRAINE`. 

You'll need to do some database cleanup. I think though that this error should have its own handling, though. And it might even make sense for us to write a helper management command... but at the very least we should document what to do.

**Comment by rtpg** [comment]
Good first issue: catching `MultipleObjectsReturned` and rethrowing it with a better error message to handle this.

**Comment by naskio** [comment]
@rtpg 
Thanks for your answer.
Yes, I thought of this solution. it makes sens to have command for this.

**Comment by AmaMidzu** [comment]
What's the status on this? Up for grabs?

**Comment by rtpg** [comment]
@AmaMidzu it's yours for the taking! Going to assign you for now just so we can keep track

**Comment by remusvitia** [comment]
Hello!
I'm new to contributing to OSS.
Can I take this up?

**Comment by remusvitia** [comment]
bump @rtpg

**Comment by fazeelghafoor** [comment]
@naskio I've figured out the first part of your recommendation. For the management command to remove duplicate tags, what do you think should be the preference?
- Remove all duplicates except the first one.
- Keep only the uppercase version, like "UKRAINE" in the example.
- If there is no uppercase version, on what basis should we remove the other tags and keep a single tag?
also what would be a suitable name for the management command? "remove_duplicate_tags" or "deduplicate_tags" or something else?

**Comment by naskio** [comment]
Hi @fazeelghafoor 
- I suggest we keep the first tag and merge all duplicates into it (relationships), then delete the duplicates.
- The name `deduplicate_tags` sounds appropriate to me.
